<?php 
	register_taxonomy( 'purpose', [ 'project' ], [
		'label'                 => 'Назначение', 
		'labels'                => [
			'name'              => 'Назначение',
			'singular_name'     => 'Назначение',
			'search_items'      => 'Поиск',
			'all_items'         => 'Все назначения',
			'view_item '        => 'Смотреть назначения',
			'parent_item'       => 'Родительское назначение',
			'parent_item_colon' => 'Родительское назначение:',
			'edit_item'         => 'Редактировать назначение',
			'update_item'       => 'Обновить назначение',
			'add_new_item'      => 'Добавить назначение',
			'new_item_name'     => 'Имя нового назначения',
			'menu_name'         => 'Назначение',
			'back_to_items'     => '← Назад',
		],
		'description'           => 'Категория определяющая назначение проектов',
		'public'                => true,
		'hierarchical'          => true,
		'rewrite'               => true,
		//'query_var'             => $taxonomy, // название параметра запроса
		'capabilities'          => array(),
		'meta_box_cb'           => null,
		'show_admin_column'     => false,
		'show_in_rest'          => null,
		'rest_base'             => null,
	]);

	register_taxonomy( 'style', [ 'project' ], [
		'label'                 => 'Стиль', 
		'labels'                => [
			'name'              => 'Стиль',
			'singular_name'     => 'Стиль',
			'search_items'      => 'Поиск стилей',
			'all_items'         => 'Все стили',
			'view_item '        => 'Смотреть стили',
			'parent_item'       => 'Родительский стиль',
			'parent_item_colon' => 'Родительский стиль:',
			'edit_item'         => 'Редактировать стиль',
			'update_item'       => 'Обновить стиль',
			'add_new_item'      => 'Добавить стиль',
			'new_item_name'     => 'Имя нового стиля',
			'menu_name'         => 'Стиль',
			'back_to_items'     => '← Назад к стилям',
		],
		'description'           => 'Категория стиля для поиска в каталоге',
		'public'                => true,
		'hierarchical'          => true,
		'rewrite'               => true,
		//'query_var'             => $taxonomy, // название параметра запроса
		'capabilities'          => array(),
		'meta_box_cb'           => null,
		'show_admin_column'     => false,
		'show_in_rest'          => null,
		'rest_base'             => null,
	]);

	register_taxonomy( 'fits', [ 'project' ], [
		'label'                 => 'Подходит для', 
		'labels'                => [
			'name'              => 'Подходит для',
			'singular_name'     => 'Подходит для',
			'search_items'      => 'Поиск',
			'all_items'         => 'Все теги',
			'view_item '        => 'Смотреть теги',
			'edit_item'         => 'Редактировать тег',
			'update_item'       => 'Обновить тег',
			'add_new_item'      => 'Добавить тег',
			'new_item_name'     => 'Имя нового тега',
			'menu_name'         => 'Подходит для',
			'back_to_items'     => '← Назад к тегам',
		],
		'description'           => 'Поиск по подходящим проектам в каталоге',
		'public'                => true,
		'hierarchical'          => true,
		'rewrite'               => true,
		//'query_var'             => $taxonomy, // название параметра запроса
		'capabilities'          => array(),
		'meta_box_cb'           => null,
		'show_admin_column'     => false,
		'show_in_rest'          => null,
		'rest_base'             => null,
	]);